#!/usr/bin/env python3
"""K-Action_orchestrator component generation dispatch (v1).
GenerationRequest v1 -> local skeleton -> component.yaml -> handoff.
Gate: review_status=approved unless --allow-unreviewed.
"""
import argparse, json, os, re, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path

VAULT = Path(os.environ.get("KA_VAULT_ROOT", ".")).resolve()
REPORTS = VAULT / ".knowledge/reports"
EVENTS = VAULT / ".knowledge/events"
INIT = VAULT / "action/K-Action_orchestrator/skills/create-action-system/scripts/init_system.py"
N = chr(10)

def now_iso():
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")

def parse_fm(text):
    fm = {}
    if text.startswith("---" + N):
        end = text.find(N + "---", 4)
        if end != -1:
            for line in text[4:end].splitlines():
                s = line.strip()
                if not s or s.startswith("#") or s.startswith("- "):
                    continue
                if ":" in s:
                    k, v = s.split(":", 1)
                    fm[k.strip()] = v.strip()
    return fm

def event(payload):
    EVENTS.mkdir(parents=True, exist_ok=True)
    f = EVENTS / ("events-" + datetime.now(timezone.utc).strftime("%Y%m%d") + ".jsonl")
    rec = {"event": "action.generation.handoff", "ts": now_iso()}
    rec.update(payload)
    with f.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(rec, ensure_ascii=False) + N)

def valid_name(name):
    return bool(re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", name))
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("command", choices=["dispatch"])
    ap.add_argument("request", nargs="?", default="-")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--allow-unreviewed", action="store_true")
    args = ap.parse_args()
    text = sys.stdin.read() if args.request == "-" else Path(args.request).read_text(encoding="utf-8", errors="ignore")
    fm = parse_fm(text)
    rid = fm.get("id") or fm.get("candidate_id") or ("gr-" + datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S"))
    name = str(fm.get("subsystem", "")).strip()
    if not valid_name(name):
        print("invalid subsystem name (lowercase, hyphen-separated): " + name, file=sys.stderr)
        return 2
    review = str(fm.get("review_status", "")).strip()
    if review != "approved" and not args.allow_unreviewed:
        print("gate: review_status must be approved (or use --allow-unreviewed)", file=sys.stderr)
        return 2
    target = VAULT / "action" / name
    if target.exists():
        print("target already exists: action/" + name, file=sys.stderr)
        return 2
    desc = str(fm.get("description", "")).strip() or ("Action subsystem: " + name)
    print(json.dumps({"dry_run": args.dry_run, "request_id": rid, "subsystem": name,
                      "target": "action/" + name, "gate": review, "github": False, "steps": 3}))
    if args.dry_run:
        print(json.dumps({"status": "dry_run_ok", "would": ["init no-github", "component.yaml", "handoff"]}))
        return 0
    if not INIT.exists():
        print("init_system.py not found: " + str(INIT), file=sys.stderr)
        return 2
    p = subprocess.run([sys.executable, str(INIT), name, "--no-github", "--description", desc, "--vault-root", str(VAULT)],
                       capture_output=True, text=True, timeout=300)
    if p.returncode != 0:
        print("init_system failed: " + p.stderr.strip()[:400], file=sys.stderr)
        return 1
    cyaml = target / "component.yaml"
    cycontent = N.join(["# Component declaration (generated by K-Action_orchestrator dispatch v1)",
                        "id: " + name, "dir:", "  - cognition/" + name, "  - action/" + name,
                        "version: 0.1.0", "provides: []", "requires: []"])
    cyaml.write_text(cycontent + N, encoding="utf-8")
    handoff = REPORTS / ("generation-handoff-" + rid + ".md")
    REPORTS.mkdir(parents=True, exist_ok=True)
    lines = ["# Generation Handoff " + rid, "",
             "> subsystem: action/" + name, "> candidate: " + fm.get("candidate_id", ""),
             "> generated_at: " + now_iso(), "> mode: local skeleton (no-github v1)", "",
             "## Next steps", "", "- 补 component.yaml provides/requires", "- 建立 cognition/" + name + " SSOT",
             "- 写接口与首个 skill/tool", "- 组件目录不会自动成为 Atomic Action", ""]
    handoff.write_text(N.join(lines), encoding="utf-8")
    event({"request_id": rid, "subsystem": name, "target": "action/" + name,
          "handoff": str(handoff.relative_to(VAULT))})
    print(json.dumps({"status": "handoff", "request_id": rid, "subsystem": name,
                      "target": "action/" + name, "handoff": str(handoff.relative_to(VAULT))}))
    return 0

if __name__ == "__main__":
    sys.exit(main())
